name: Release and Publish

on:
  push:
    #tags:
    #  - "v*"
  workflow_dispatch:
    inputs:
      releaseTag:
        description: "Release tag to publish"
        type: string
        required: true

env:
  IMG: acrpullci.azurecr.io/msi-acrpull:latest

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Get image metadata
      id: get_metadata
      run: |
        if [ "${{ github.event_name }}" == "push" ]; then
          echo "IMG_TAG=${{ github.ref }}" >> $env.GITHUB_OUTPUT
        else
          echo "IMG_TAG=${{ github.event.inputs.releaseTag }}" >> $env.GITHUB_OUTPUT
        fi
        echo "IMG=acrpullci.azurecr.io/msi-acrpull:${IMG_TAG}" >> $env.GITHUB_OUTPUT
        echo "${IMG_TAG}"
        echo "${IMG}"
    outputs:
      IMG_TAG: ${{ steps.get_metadata.outputs.IMG_TAG }}
      IMG: ${{ steps.get_metadata.outputs.IMG }}

  release:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: verify output
      run: |
        echo "tag: ${{ needs.setup.outputs.IMG_TAG }}"
        echo "image ${{ needs.setup.outputs.IMG }}"

  publish:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Build the Docker image
      run: make docker-build

    - name: Azure Container Registry Login
      if: github.event_name == 'push'
      uses: Azure/docker-login@v1
      with:
        login-server: acrpullci.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Push to CI ACR
      if: github.event_name == 'push'
      run: make docker-push
